# Basic site settings
base_url = "https://yourusername.github.io"
title = "Your Personal Website"
default_language = "en"
description = "A personal website showcasing my work and skills."

# Optional settings
highlight_code = true
compile_sass = true
build_search_index = true

# Theme settings (optional)
[extra]
  theme = "your-theme-name"
  site_description = "A personal website"
  social_links = [
    { name = "GitHub", url = "https://github.com/yourusername" },
    { name = "LinkedIn", url = "https://www.linkedin.com/in/matthew-holden86/" },
  ]

# Taxonomies (optional)
[taxonomies]
  [[taxonomies]]
  name = "tags"
  [[taxonomies]]
  name = "categories"
