# Basic site settings
base_url = "https://matthold86.github.io"
title = "Your Personal Website"
default_language = "en"
description = "Personal Portfolio and Website."

# Optional settings
highlight_code = true
compile_sass = true
build_search_index = true

# Theme settings (optional)
#[extra]
#  site_description = "A personal website"
#  social_links = [
#    { name = "GitHub", url = "https://github.com/yourusername" },
#    { name = "LinkedIn", url = "https://www.linkedin.com/in/matthew-holden86/" },
#  ]